azure:
  activedirectory:
    keydiscoveryurl: https://login.microsoftonline.com/common/discovery/keys
    tenant-id: YOUR_TENANT_ID_HERE
    client-id: YOUR_CLIENT_ID_HERE
    client-secret: 'YOUR_CLIENT_SECRET_HERE'
    post-logout-redirect-uri: http://localhost:8080
    authorization-clients:
      graph:
        scopes: user.read, mail.read
      apponly:
        authorization-grant-type: client-credentials
        scopes: https://graph.microsoft.com/.default

app:
  protect:
    authenticated: /delegated, /apponly

notifications:
  host: YOUR_NGROK_PROXY_URL_HERE

certificate:
  storename: JKSkeystore.jks
  storepass: poiqwe1!
  alias: selfsignedjks
